### PR TITLE
Fixed App Install

### PR DESCRIPTION
**Pull request by andrewgosselin-nt**
The main issue with installing and enabling apps by default is that is has to be done during a very specific period.

The install for nextcloud has to be done, which means you have to have bash wait until it is, doing the installing during the installation of nextcloud is how they do it, behind a version checker. A pull request for this does exist, although it is for installation so I will have to make another pull request for the enabling of apps at some point.

I think the best course of action and really the only one at this point is to replace the entrypoint.sh and not run the default one.
I have tried stripping out everything but the commands end up not registering because of the install.

### CODE REVIEW

**Comment by ZacharySeebeckNewtech** [comment]
oop

**Comment by andrewgosselin-nt** [comment]
Dont actually push this yet, adding in 2 more variables for MAKE and ENABLE.

**Comment by andrewgosselin-nt** [comment]
@scott.lewis In this update, I added 3 different env variables, I updated the env for mail app in the docs site. Now everything is done automatically, the make dev-setup is ran, the app is fully autodeployed.
Andrew Gosselin
09:33 am
the main issue is that it takes ages cause it has to run the make dev-setup
Andrew Gosselin
09:33 am
but i dont think thats avoidable.
Andrew Gosselin
09:33 am
and its probably faster on the server.

`NEXTCLOUD_INSTALL_APPS="ntsso mail"
NEXTCLOUD_MAKE_APPS="mail"
NEXTCLOUD_ENABLE_APPS="ntsso mail"`

**Comment by ZacharySeebeckNewtech** [comment]
Can you update the env in docs too @andrewgosselin-nt ?

**Comment by ZacharySeebeckNewtech** [comment]
I'm blind.
Sorry @andrewgosselin-nt

**Pull request merged**
